# **Assignment 2**
**Question 1**


For this assignment you'll be looking at 2017 data on immunizations from the CDC. Your datafile for this assignment is in assets/NISPUF17.csv. A data users guide for this, which you'll need to map the variables in the data to the questions being asked, is available at assets/NIS-PUF17-DUG.pdf. Note: you may have to go to your Jupyter tree (click on the Coursera image) and navigate to the assignment 2 assets folder to see this PDF file).

Write a function called proportion_of_education which returns the proportion of children in the dataset who had a mother with the education levels equal to less than high school (<12), high school (12), more than high school but not a college graduate (>12) and college degree.

This function should return a dictionary in the form of (use the correct numbers, do not round numbers):

    {"less than high school":0.2,
    "high school":0.4,
    "more than high school but not college":0.2,
    "college":0.2}

In [ ]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
src = '/content/NISPUF17.zip'
df = pd.read_csv(src, compression='zip')

df_meduc = df["EDUC1"]
def proportion_of_education():
  proportion_of_education_dict = {"less than high school": (len(df_meduc[df_meduc==1]))/len(df_meduc),
                                "high school": (len(df_meduc[df_meduc==2]))/len(df_meduc),
                                "more than high school but not college": (len(df_meduc[df_meduc==3]))/len(df_meduc),
                                "college":(len(df_meduc[df_meduc==4]))/len(df_meduc)}

  print(proportion_of_education_dict)
proportion_of_education()

FileNotFoundError: [Errno 2] No such file or directory: '/content/NISPUF17.zip'

**Question 2**

Let's explore the relationship between being fed breastmilk as a child and getting a seasonal influenza vaccine from a healthcare provider. Return a tuple of the average number of influenza vaccines for those children we know received breastmilk as a child and those who know did not.

This function should return a tuple in the form (use the correct numbers:

(2.5, 0.1)

In [ ]:
# CBF_01 ->  child ever fed breast milk,
# 99 for missing values, 1 for Yes, 2 for No, 77 for Don't know

df_q2 = df.loc[:,["CBF_01","P_NUMFLU"]]
df_q2 = df_q2.dropna()
df_q2_fed = df_q2[df_q2["CBF_01"] == 1]
df_q2_notfed = df_q2[df_q2["CBF_01"] == 2]
avg_fed_vac = np.sum(df_q2_fed["P_NUMFLU"])/len(df_q2_fed)
avg_notfed_vac = np.sum(df_q2_notfed["P_NUMFLU"])/len(df_q2_notfed)
len((avg_fed_vac,avg_notfed_vac)) == 2

(1.8799187420058687,1.5963945918878317)

**Question 3**

It would be interesting to see if there is any evidence of a link between vaccine effectiveness and sex of the child. Calculate the ratio of the number of children who contracted chickenpox but were vaccinated against it (at least one varicella dose) versus those who were vaccinated but did not contract chicken pox. Return results by sex.

This function should return a dictionary in the form of (use the correct numbers):

    {"male":0.2,
    "female":0.4}

Note: To aid in verification, the chickenpox_by_sex()['female'] value the autograder is looking for starts with the digits 0.0077.

In [ ]:
# SEX -> 1 for MALE, 2 for FEMALE
# HAD_CPOX -> 1 -> 1 for YES, 2 for NO, 77 for Don't know, 99 for Missing

df_had_cpox = df.loc[:,["SEX","HAD_CPOX","P_NUMVRC"]]
df_had_cpox = df_had_cpox.dropna()
df_hadnot_cpox = df_had_cpox[df_had_cpox["HAD_CPOX"]==2]
df_hadnot_cpox_male = df_hadnot_cpox[df_hadnot_cpox["SEX"]==1]
df_hadnot_cpox_female = df_hadnot_cpox[df_hadnot_cpox["SEX"]==2]
df_had_cpox = df_had_cpox[df_had_cpox["HAD_CPOX"]==1]
df_had_cpox_male = df_had_cpox[df_had_cpox["SEX"]==1]
df_had_cpox_female = df_had_cpox[df_had_cpox["SEX"]==2]
cpox_dict = {"Rate of male who contracted cpox but were vaccinated": len(df_had_cpox_male[df_had_cpox_male["P_NUMVRC"]>0])/len(df_had_cpox_male),
             "Rate of female who contracted cpox but were vaccinated": len(df_had_cpox_female[df_had_cpox_female["P_NUMVRC"]>0])/len(df_had_cpox_female),
             "Rate of male who did not contracted cpox but were vaccinated": len(df_hadnot_cpox_male[df_hadnot_cpox_male["P_NUMVRC"]>0])/len(df_hadnot_cpox_male),
             "Rate of female who did not contracted cpox but were vaccinated": len(df_hadnot_cpox_female[df_hadnot_cpox_female["P_NUMVRC"]>0])/len(df_hadnot_cpox_female),}

print(cpox_dict)

{'Rate of male who contracted cpox but were vaccinated': 0.7010309278350515, 'Rate of female who contracted cpox but were vaccinated': 0.6973684210526315, 'Rate of male who did not contracted cpox but were vaccinated': 0.9128458241330043, 'Rate of female who did not contracted cpox but were vaccinated': 0.9174534664148908}


**Question 4**

A correlation is a statistical relationship between two variables. If we wanted to know if vaccines work, we might look at the correlation between the use of the vaccine and whether it results in prevention of the infection or disease [1]. In this question, you are to see if there is a correlation between having had the chicken pox and the number of chickenpox vaccine doses given (varicella).

Some notes on interpreting the answer. The had_chickenpox_column is either 1 (for yes) or 2 (for no), and the num_chickenpox_vaccine_column is the number of doses a child has been given of the varicella vaccine. A positive correlation (e.g., corr > 0) means that an increase in had_chickenpox_column (which means more noâ€™s) would also increase the values of num_chickenpox_vaccine_column (which means more doses of vaccine). If there is a negative correlation (e.g., corr < 0), it indicates that having had chickenpox is related to an increase in the number of vaccine doses.

Also, pval is the probability that we observe a correlation between had_chickenpox_column and num_chickenpox_vaccine_column which is greater than or equal to a particular value occurred by chance. A small pval means that the observed correlation is highly unlikely to occur by chance. In this case, pval should be very small (will end in e-18 indicating a very small number).

[1] This isnâ€™t really the full picture, since we are not looking at when the dose was given. Itâ€™s possible that children had chickenpox and then their parents went to get them the vaccine. Does this dataset have the data we would need to investigate the timing of the dose?

In [ ]:
import scipy.stats as stats

def corr_chickenpox():
    cpox_ = df[df['HAD_CPOX'].isin([1, 2])][['HAD_CPOX', 'P_NUMVRC']].dropna()
    corr, pval = stats.pearsonr(cpox_['HAD_CPOX'], cpox_['P_NUMVRC'])
    return corr
    raise NotImplementedError()

corr_chickenpox()

np.float64(0.07044873460147985)

# Pandas Uygulama SorularÄ±

## Soru 1: Ã–ÄŸrenci NotlarÄ±nÄ±n Temizlenmesi ve Analizi

Bir okulun Ã¶ÄŸrenci notlarÄ±nÄ± iÃ§eren "student_grades.csv" adlÄ± bir CSV dosyasÄ± verilmiÅŸ. Dosyada ÅŸu sÃ¼tunlar bulunuyor:

- **Student**: Ã–ÄŸrencinin tam adÄ± (Ã¶r. "Ahmet YÄ±lmaz")
- **Subject**: Ders adÄ±
- **Grade**: Not (bazÄ± giriÅŸler "85", bazÄ±larÄ± "85 puan" gibi tutarsÄ±z formatta)
- **Date**: SÄ±nav tarihi (Ã¶r. "2023-10-15", "15/10/2023" gibi farklÄ± formatlarda)

Ancak veri setinde bazÄ± sorunlar var:
- "Grade" sÃ¼tununda bazÄ± notlar metin iÃ§eriyor (Ã¶r. "85 puan").
- "Date" sÃ¼tununda tarih formatlarÄ± tutarsÄ±z.
- BazÄ± satÄ±rlarda eksik deÄŸerler (None) var.

**GÃ¶revlerin:**
a. Veri setini bir pandas DataFrame'e yÃ¼kle.  
b. "Grade" sÃ¼tununu temizle; metinleri kaldÄ±rÄ±p tÃ¼m deÄŸerleri sayÄ±sal (float) hale getir.  
c. "Date" sÃ¼tununu standart bir datetime formatÄ±na Ã§evir (Ã¶r. "YYYY-MM-DD").  
d. Eksik "Grade" deÄŸerlerini o dersin ortalamasÄ±yla doldur.  
e. Her ders iÃ§in ortalama notu hesapla.  
f. En yÃ¼ksek ortalama nota sahip dersi bul.

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/student_grades.csv")

df["Grade"] = df["Grade"].str.extract("([\d]{1,3})(?:\s[\w]*)?")

def fix_date(x):
  if isinstance(x, str):
    x = x.strip()
    if "/" in x:
      return pd.to_datetime(x, dayfirst=True, errors="coerce")
    else:
      return pd.to_datetime(x, errors="coerce")
  return pd.NaT

df["Date"] = df["Date"].apply(fix_date)
df["Date"] = pd.to_datetime(df["Date"])

df["Grade"] = pd.to_numeric(df["Grade"], errors="coerce")

def find_average_and_write(row):
  if pd.isna(row["Grade"]):
    average = int(np.mean(df[df["Subject"]==row["Subject"]]["Grade"].dropna()))
    row["Grade"] = average
    return row
  else:
    return row

df = df.apply(find_average_and_write,axis="columns")

for subject in list(df["Subject"].unique()):
  ortalama = np.mean(df[df["Subject"] == subject]["Grade"])
  print(f"{subject} dersinin ortalamasÄ±: {ortalama}")

df

Matematik dersinin ortalamasÄ±: 53.75
Fen Bilgisi dersinin ortalamasÄ±: 46.15
TÃ¼rkÃ§e dersinin ortalamasÄ±: 37.65
Sosyal Bilgiler dersinin ortalamasÄ±: 54.55
Ä°ngilizce dersinin ortalamasÄ±: 56.6

          Student          Subject  Grade       Date
0      Sultan KoÃ§        Matematik   67.0 2023-01-04
1      Sultan KoÃ§      Fen Bilgisi   46.0 2023-02-07
2      Sultan KoÃ§           TÃ¼rkÃ§e   94.0 2023-08-05
3      Sultan KoÃ§  Sosyal Bilgiler   95.0 2023-07-27
4      Sultan KoÃ§        Ä°ngilizce   20.0 2023-05-08
..            ...              ...    ...        ...
95  HÃ¼seyin AydÄ±n        Matematik   80.0 2023-02-20
96  HÃ¼seyin AydÄ±n      Fen Bilgisi   30.0 2023-04-15
97  HÃ¼seyin AydÄ±n           TÃ¼rkÃ§e   17.0 2023-12-21
98  HÃ¼seyin AydÄ±n  Sosyal Bilgiler   54.0 2023-01-15
99  HÃ¼seyin AydÄ±n        Ä°ngilizce   50.0 2023-09-10

[100 rows x 4 columns]

# Assignment - Module 3
**Question 1**

Load the energy data from the file assets/Energy Indicators.xls, which is a list of indicators of energy supply and renewable electricity production from the United Nations for the year 2013, and should be put into a DataFrame with the variable name of Energy.

Keep in mind that this is an Excel file, and not a comma separated values file. Also, make sure to exclude the footer and header information from the datafile. The first two columns are unneccessary, so you should get rid of them, and you should change the column labels so that the columns are:

['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable]

Convert Energy Supply to gigajoules (Note: there are 1,000,000 gigajoules in a petajoule). For all countries which have missing data (e.g. data with "...") make sure this is reflected as np.NaN values.

Rename the following list of countries (for use in later questions):

"Republic
"United States of America": "United States",
"United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
"China, Hong Kong Special Administrative Region": "Hong Kong"```

There are also several countries with numbers and/or parenthesis in their name. Be sure to remove these, e.g. `'Bolivia (Plurinational State of)'` should be `'Bolivia'`.  `'Switzerland17'` should be `'Switzerland'`.

Next, load the GDP data from the file `assets/world_bank.csv`, which is a csv containing countries' GDP from 1960 to 2015 from [World Bank](http://data.worldbank.org/indicator/NY.GDP.MKTP.CD). Call this DataFrame **GDP**.

Make sure to skip the header, and rename the following list of countries:

```"Korea, Rep.": "South Korea",
"Iran, Islamic Rep.": "Iran",
"Hong Kong SAR, China": "Hong Kong"```

Finally, load the [Sciamgo Journal and Country Rank data for Energy Engineering and Power Technology](http://www.scimagojr.com/countryrank.php?category=2102) from the file `assets/scimagojr-3.xlsx`, which ranks countries based on their journal contributions in the aforementioned area. Call this DataFrame **ScimEn**.

Join the three datasets: GDP, Energy, and ScimEn into a new dataset (using the intersection of country names). Use only the last 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15).

The index of this DataFrame should be the name of the country, and the columns should be ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy Supply',
       'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015'].

*This function should return a DataFrame with 20 columns and 15 entries, and the rows of the DataFrame should be sorted by "Rank".*

In [ ]:
import pandas as pd
import numpy as np
import re

pd.set_option('future.no_silent_downcasting', True)

energy_df = pd.read_excel("/content/Energy Indicators.xls",
                   skiprows=17,
                   usecols=[2,3,4,5],
                   names=["Country","Energy Supply","Energy Supply per Capita","% Renewable"],
                   nrows=227)

energy_df = energy_df.replace(["...",0.0,0,"United Kingdom of Great Britain and Northern Ireland19","China, Hong Kong Special Administrative Region3","United States of America20","Republic of Korea"]
                              ,[np.nan,np.nan,np.nan,"United Kingdom","Hong Kong","United States","South Korea"])

energy_df["Country"] = energy_df["Country"].str.extract("([a-zA-Z,\-Ã´\'Ã© ]*)(?:[\d]*)?")[0].str.strip()
energy_df["Energy Supply"] = energy_df["Energy Supply"] * 1000000

GDP = pd.read_csv("/content/world_bank.csv",skiprows=4)
GDP = GDP.replace(["Korea, Rep.","Iran, Islamic Rep.","Hong Kong SAR, China"],["South Korea","Iran","Hong Kong"])
GDP = GDP.rename(columns={"Country Name":"Country"})

ScimEn = pd.read_excel("/content/scimagojr-3.xlsx")

ara_df = pd.merge(energy_df,GDP,on="Country",how="inner")
son_df = pd.merge(ScimEn,ara_df,how="inner",on="Country")

#GDP["Country"].unique()
#energy_df["Country"].unique()

final_df = son_df.sort_values(by="Rank").head(15)
columns_to_keep = ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']
final_df = final_df.set_index("Country")[columns_to_keep]
final_df

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,127191000000,93,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,90838000000,286,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,18984000000,149,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7920000000,124,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,30709000000,214,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,10431000000,296,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,13261000000,165,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,33195000000,26,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,10597000000,166,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,11007000000,221,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,6530000000,109,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,4923000000,106,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13,8896,8819,57470,19125,6.46,72,9172000000,119,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14,8831,8725,90765,15606,10.28,107,5386000000,231,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,12149000000,59,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

**Question 2**

The previous question joined three datasets then reduced this to just the top 15 entries. When you joined the datasets, but before you reduced this to the top 15 items, how many entries did you lose?

161-15=146

**Question 3**

What are the top 15 countries for average GDP over the last 10 years?

This function should return a Series named avgGDP with 15 countries and their average GDP sorted in descending order.

In [ ]:
def avgGDPcalc(x):
  return pd.Series(np.nanmean([x["2006"],x["2007"],x["2008"],x["2009"],x["2010"],x["2011"],x["2012"],x["2013"],x["2014"],x["2015"]]),name="Average GDP")

avgGDP = final_df.apply(avgGDPcalc,axis="columns").sort_values(by=0,ascending=False)[0]
type(avgGDP)

pandas.core.series.Series

**Question 4**

By how much had the GDP changed over the 10 year span for the country with the 6th largest average GDP?

This function should return a single number.

In [ ]:
float(final_df.loc[avgGDP.index[5],"2015"] - final_df.loc[avgGDP.index[5],"2006"])

NameError: name 'final_df' is not defined

**Question 5**

What is the mean energy supply per capita?

This function should return a single number.

In [ ]:
float(np.mean(final_df["Energy Supply per Capita"]))

157.6

**Question 6**

What country has the maximum % Renewable and what is the percentage?

This function should return a tuple with the name of the country and the percentage.

In [ ]:
(final_df["% Renewable"].idxmax(),final_df["% Renewable"].max())

NameError: name 'final_df' is not defined

**Question 7**

Create a new column that is the ratio of Self-Citations to Total Citations. What is the maximum value for this new column, and what country has the highest ratio?

This function should return a tuple with the name of the country and the ratio.

In [ ]:
final_df["ratio of Self-Citations to Total Citations"] = final_df["Self-citations"] / final_df["Citations"]
(final_df["ratio of Self-Citations to Total Citations"].idxmax(),final_df["ratio of Self-Citations to Total Citations"].max())

NameError: name 'final_df' is not defined

**Question 8**

Create a column that estimates the population using Energy Supply and Energy Supply per capita. What is the third most populous country according to this estimate?

This function should return the name of the country.

In [ ]:
final_df["Population"] = final_df["Energy Supply"] / final_df["Energy Supply per Capita"]
print(final_df["Population"].sort_values(ascending=False).index[2])
final_df

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2008,2009,2010,2011,2012,2013,2014,2015,ratio of Self-Citations to Total Citations,Population
Country,,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,127191000000,93,19.754910,...,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,0.689313,1367645161.290323
United States,2,96661,94747,792274,265436,8.20,230,90838000000,286,11.570980,...,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,0.335031,317615384.615385
Japan,3,30504,30287,223024,61554,7.31,134,18984000000,149,10.232820,...,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,0.275997,127409395.973154
United Kingdom,4,20944,20357,206091,37874,9.84,139,7920000000,124,10.600470,...,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,0.183773,63870967.741935
Russian Federation,5,18534,18301,34266,12422,1.85,57,30709000000,214,17.288680,...,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,0.362517,143500000.0
Canada,6,17899,17620,215003,40930,12.01,149,10431000000,296,61.945430,...,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,0.190369,35239864.864865
Germany,7,17027,16831,140566,27426,8.26,126,13261000000,165,17.901530,...,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,0.195111,80369696.969697
India,8,15005,14841,128763,37209,8.58,115,33195000000,26,14.969080,...,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,0.288973,1276730769.230769
France,9,13153,12973,130632,28601,9.93,114,10597000000,166,17.020280,...,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,0.218943,63837349.39759
South Korea,10,11983,11923,114675,22595,9.57,104,11007000000,221,2.279353,...,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,0.197035,49805429.864253
Italy,11,10964,10794,111850,26661,10.20,106,6530000000,109,33.667230,...,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,0.238364,59908256.880734
Spain,12,9428,9330,123336,23964,13.08,115,4923000000,106,37.968590,...,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,0.194299,46443396.226415
Iran,13,8896,8819,57470,19125,6.46,72,9172000000,119,5.707721,...,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN,0.332782,77075630.252101
Australia,14,8831,8725,90765,15606,10.28,107,5386000000,231,11.810810,...,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,0.171939,23316017.316017
Brazil,15,8668,8596,60702,14396,7.00,86,12149000000,59,69.648030,...,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,0.237159,205915254.237288

**Question 9**

Create a column that estimates the number of citable documents per person. What is the correlation between the number of citable documents per capita and the energy supply per capita? Use the .corr() method, (Pearson's correlation).

This function should return a single number.

(Optional: Use the built-in function plot9() to visualize the relationship between Energy Supply per Capita vs. Citable docs per Capita)

In [ ]:
final_df["Citable documents per Person"] = final_df["Citations"] / final_df["Population"]

float(final_df["Citable documents per Person"].corr(final_df["Energy Supply per Capita"]))

0.6668248468590926

**Question 10**

Create a new column with a 1 if the country's % Renewable value is at or above the median for all countries in the top 15, and a 0 if the country's % Renewable value is below the median.

This function should return a series named HighRenew whose index is the country name sorted in ascending order of rank.

In [ ]:
def renewable_median(row):
  median_value = np.median(final_df["% Renewable"])
  if row["% Renewable"] >= median_value:
    return 1
  else:
    return 0

final_df["Renewable Rank"] = final_df.apply(renewable_median,axis="columns")
final_df["Renewable Rank"].sort_values(ascending=True)

Country
United States         0
Japan                 0
United Kingdom        0
India                 0
Iran                  0
Australia             0
South Korea           0
China                 1
Germany               1
Canada                1
Russian Federation    1
France                1
Spain                 1
Italy                 1
Brazil                1
Name: Renewable Rank, dtype: int64

**Question 11**

Use the following dictionary to group the Countries by Continent, then create a DataFrame that displays the sample size (the number of countries in each continent bin), and the sum, mean, and std deviation for the estimated population of each country.


```
ContinentDict  = {'China':'Asia',
                  'United States':'North America',
                  'Japan':'Asia',
                  'United Kingdom':'Europe',
                  'Russian Federation':'Europe',
                  'Canada':'North America',
                  'Germany':'Europe',
                  'India':'Asia',
                  'France':'Europe',
                  'South Korea':'Asia',
                  'Italy':'Europe',
                  'Spain':'Europe',
                  'Iran':'Asia',
                  'Australia':'Australia',
                  'Brazil':'South America'}
```



This function should return a DataFrame with index named Continent ['Asia', 'Australia', 'Europe', 'North America', 'South America'] and columns ['size', 'sum', 'mean', 'std']

In [ ]:
ContinentDict  = {'China':'Asia',
                  'United States':'North America',
                  'Japan':'Asia',
                  'United Kingdom':'Europe',
                  'Russian Federation':'Europe',
                  'Canada':'North America',
                  'Germany':'Europe',
                  'India':'Asia',
                  'France':'Europe',
                  'South Korea':'Asia',
                  'Italy':'Europe',
                  'Spain':'Europe',
                  'Iran':'Asia',
                  'Australia':'Australia',
                  'Brazil':'South America'}

final_df["Continent"] = ContinentDict
summary_by_continent = final_df.groupby("Continent").agg(
    size = ("Population","size"),
    sum = ("Population","sum"),
    mean = ("Population","mean"),
    std = ("Population","std")
)
summary_by_continent

NameError: name 'final_df' is not defined

**Question 12**

Cut % Renewable into 5 bins. Group Top15 by the Continent, as well as these new % Renewable bins. How many countries are in each of these groups?

This function should return a Series with a MultiIndex of Continent, then the bins for % Renewable. Do not include groups with no countries.

In [ ]:
final_df["% Renewable Cutted"] = pd.cut(final_df["% Renewable"],5)
final_df.groupby(["Continent","% Renewable Cutted"])["Continent"].agg(np.size).dropna()

/tmp/ipython-input-170-3868571115.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  final_df.groupby(["Continent","% Renewable Cutted"])["Continent"].agg(np.size).dropna()

Continent      % Renewable Cutted
Asia           (2.212, 15.753]       4.0
               (15.753, 29.227]      1.0
Australia      (2.212, 15.753]       1.0
Europe         (2.212, 15.753]       1.0
               (15.753, 29.227]      3.0
               (29.227, 42.701]      2.0
North America  (2.212, 15.753]       1.0
               (56.174, 69.648]      1.0
South America  (56.174, 69.648]      1.0
Name: Continent, dtype: float64

**Question 13**

Convert the Population Estimate series to a string with thousands separator (using commas). Use all significant digits (do not round the results).

e.g. 12345678.90 -> 12,345,678.90

This function should return a series PopEst whose index is the country name and whose values are the population estimate string

In [ ]:
"""def thousand_seperator(data):
  strdata = str(data)
  wholelendata = len(strdata) -1
  lendata = len(str(int(float(data))))
  first_comma_place = lendata % 3
  first_comma_place_index = first_comma_place - 1
  result = ""
  for i in range(lendata):
    if i <= first_comma_place_index or i == 0:
      result += strdata[i]
    elif (lendata - i)%3==0:
      result = result + "," + strdata[i]
    else:
      result += strdata[i]

  result = result + "." + strdata[-(wholelendata-lendata):]

  return result"""


final_df["Population"] = final_df["Population"].apply('{:,}'.format)
final_df

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2008,2009,2010,2011,2012,2013,2014,2015,ratio of Self-Citations to Total Citations,Population
Country,,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,127191000000,93,19.754910,...,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,0.689313,"1,367,645,161.2903225"
United States,2,96661,94747,792274,265436,8.20,230,90838000000,286,11.570980,...,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,0.335031,"317,615,384.61538464"
Japan,3,30504,30287,223024,61554,7.31,134,18984000000,149,10.232820,...,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,0.275997,"127,409,395.97315437"
United Kingdom,4,20944,20357,206091,37874,9.84,139,7920000000,124,10.600470,...,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,0.183773,"63,870,967.741935484"
Russian Federation,5,18534,18301,34266,12422,1.85,57,30709000000,214,17.288680,...,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,0.362517,"143,500,000.0"
Canada,6,17899,17620,215003,40930,12.01,149,10431000000,296,61.945430,...,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,0.190369,"35,239,864.86486486"
Germany,7,17027,16831,140566,27426,8.26,126,13261000000,165,17.901530,...,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,0.195111,"80,369,696.96969697"
India,8,15005,14841,128763,37209,8.58,115,33195000000,26,14.969080,...,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,0.288973,"1,276,730,769.2307692"
France,9,13153,12973,130632,28601,9.93,114,10597000000,166,17.020280,...,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,0.218943,"63,837,349.39759036"
South Korea,10,11983,11923,114675,22595,9.57,104,11007000000,221,2.279353,...,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,0.197035,"49,805,429.864253394"
Italy,11,10964,10794,111850,26661,10.20,106,6530000000,109,33.667230,...,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,0.238364,"59,908,256.880733944"
Spain,12,9428,9330,123336,23964,13.08,115,4923000000,106,37.968590,...,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,0.194299,"46,443,396.2264151"
Iran,13,8896,8819,57470,19125,6.46,72,9172000000,119,5.707721,...,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN,0.332782,"77,075,630.25210084"
Australia,14,8831,8725,90765,15606,10.28,107,5386000000,231,11.810810,...,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,0.171939,"23,316,017.316017315"
Brazil,15,8668,8596,60702,14396,7.00,86,12149000000,59,69.648030,...,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,0.237159,"205,915,254.23728815"

# Pandas Practice Questions

Part 1: Data Loading and Preparation

Load employees.csv into a DataFrame. Standardize column names (lowercase, no spaces).

Clean the full_name column: separate into first_name and last_name, remove parenthetical text.

Handle missing data:

salary: fill with the median salary per department.

hire_date, gender: fill with "Unknown".

Convert hire_date to datetime objects (handle errors gracefully).

Create salary_tier (4 equal-width bins) from salary.

Load project_assignments.csv and project_details.csv.

Standardize their column names.

In project_assignments, rename eid to employee_id.

Convert start_date and end_date in project_details to datetime objects (handle errors gracefully).

Part 2: Data Merging

Merge employees and project_assignments using an outer join to create employee_assignments.

Merge employee_assignments and project_details using a left join to create master_df.

Part 3: Analysis and GroupBy Operations

Using master_df, calculate:

Mean salary, total budget, and average hours assigned per department.

Total employees and average employee salary per project.

Create high_salary_projects containing projects where the average employee salary exceeds $100,000.

Add a new column avg_dept_salary to master_df (average salary per department). Then, create salary_diff_from_dept (difference between an employee's salary and their department's average).

Generate a pivot table: index department, columns project_status, values hours_assigned (summed). Include margins.

Part 4: Specific Questions

Identify the top five employees by salary.

Determine the total budget for all "In Progress" projects.

Count employees hired in 2022.

Find the average hours assigned to employees in the "Engineering" department.

List full_name of all employees not assigned to any project.

In [ ]:
import pandas as pd
import numpy as np

def standartize_col_names(df):
  df.columns = [col.lower().strip().replace(" ","_") for col in df.columns]
  return df

employees_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/datasets/employees.csv")
employees_df = standartize_col_names(employees_df)

employees_df["full_name"] = employees_df["full_name"].str.replace(r"\s*\(.*\)","",regex=True).str.strip()
employees_df["first_name"] = employees_df["full_name"].str.split(",").str.get(-1).str.strip()
employees_df["last_name"] = employees_df["full_name"].str.split(",").str.get(0).str.strip()

employees_df = employees_df.drop(columns=['full_name'])

employees_df["salary"] = pd.to_numeric(employees_df["salary"], errors='coerce')
employees_df["salary"] = employees_df["salary"].fillna(employees_df["salary"].median())
employees_df["gender"] = employees_df["gender"].fillna("Unknown")

employees_df["hire_date"] = pd.to_datetime(employees_df["hire_date"],errors="coerce")

employees_df["hire_date"] = employees_df["hire_date"].fillna("Unknown")

salary_category = pd.CategoricalDtype(categories=[1, 2, 3, 4], ordered=True)
employees_df["salary_tier"] = pd.cut(employees_df["salary"],4,labels=[1,2,3,4]).astype(salary_category)

project_assignments = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/datasets/project_assignments.csv")
project_details = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/datasets/project_details.csv")

project_assignments = standartize_col_names(project_assignments)
project_details = standartize_col_names(project_details)

project_assignments = project_assignments.rename(columns={"eid":"employee_id"})

project_details["start_date"] = pd.to_datetime(project_details["start_date"], errors='coerce')
project_details["end_date"] = pd.to_datetime(project_details["end_date"], errors='coerce')

employee_assignments = pd.merge(employees_df,project_assignments,how="outer",on="employee_id")
master_df = pd.merge(employee_assignments,project_details,how="left",on="project_code")

print("Average salary is",int(master_df.groupby("employee_id").agg({"salary":"mean"}).mean().iloc[0]))
print("Total budget is",int(master_df["budget"].sum()))

print(master_df.groupby("department").agg({"hours_assigned":"mean"}))

project_analysis = master_df.groupby("project_code").agg(
                    Total_Employees = ("project_code","size"),
                    Average_Employee_Salary_per_Project = ("salary","mean"))

print(project_analysis)

print(project_analysis[project_analysis["Average_Employee_Salary_per_Project"]>100000])

master_df["avg_dept_salary"] = master_df["department"].map(employees_df.groupby("department")["salary"].mean())

#.map() nasÄ±l Ã§alÄ±ÅŸÄ±r??
#1.adÄ±m iÃ§ine nasÄ±l bir series atacaÄŸÄ±z?
#bizim iÃ§ine attÄ±ÄŸÄ±mÄ±z bu ÅŸekilde:
# 	salary
#department
#Engineering 	114285.714286
#HR 	91000.000000
#Marketing 	83750.000000
#Sales 	82400.000000
#burada yaptÄ±ÄŸÄ±mÄ±z departmana gÃ¶re ortalama salary girmek

"""Åžimdi .map()'in adÄ±m adÄ±m ne yaptÄ±ÄŸÄ±nÄ± gÃ¶relim:

    Hedef Series'i SeÃ§me: Pandas, master_df['department'] Series'indeki ilk elemandan baÅŸlar. Diyelim ki bu Engineering.

    EÅŸleme Nesnesinde Arama (Indeksleme): .map(), bu Engineering deÄŸerini alÄ±r ve avg_dept_salary_map Series'inin indeksinde bu deÄŸere karÅŸÄ±lÄ±k gelen bir eÅŸleÅŸme arar.

    DeÄŸeri Ã‡ekme: avg_dept_salary_map Series'inde Engineering indeksine karÅŸÄ±lÄ±k gelen deÄŸer 102500.0 bulunur.

    Yeni DeÄŸeri OluÅŸturma: Bu 102500.0 deÄŸeri, master_df'deki o satÄ±rÄ±n (yani Engineering departmanÄ± olan satÄ±rÄ±n) avg_dept_salary sÃ¼tununa yazÄ±lacak olan deÄŸerdir.

    Sonraki Elemana GeÃ§me: Bu iÅŸlem, master_df['department'] Series'indeki bir sonraki eleman iÃ§in tekrarlanÄ±r.

        EÄŸer bir sonraki eleman yine Engineering ise, yine avg_dept_salary_map'teki Engineering indeksine bakar ve yine 102500.0 deÄŸerini getirir.

        EÄŸer bir sonraki eleman Marketing ise, avg_dept_salary_map'teki Marketing indeksine bakar ve 82000.0 deÄŸerini getirir.

    EÅŸleÅŸme BulunamamasÄ± Durumu: EÄŸer master_df['department'] iÃ§inde avg_dept_salary_map'in indeksinde bulunmayan bir departman adÄ± olsaydÄ± (Ã¶rneÄŸin 'R&D' diye bir departman olsaydÄ± ama avg_dept_salary_map iÃ§inde olmasaydÄ±), o zaman .map() varsayÄ±lan olarak NaN (Not a Number) veya NaT (Not a Time) deÄŸeri atardÄ±."""

master_df["salary_diff_from_dept"] = np.abs(master_df["salary"]-master_df["avg_dept_salary"])
master_df

Average salary is 95550
Total budget is 7580000
             hours_assigned
department
Engineering           30.80
HR                    21.00
Marketing             28.75
Sales                 30.00
              Total_Employees  Average_Employee_Salary_per_Project
project_code
P-ENG-01                    5                             111000.0
P-ENG-02                    4                             116250.0
P-FIN-01                    1                              95000.0
P-HR-01                     2                              90500.0
P-MKT-01                    2                              80500.0
P-MKT-02                    2                              86500.0
P-SAL-01                    2                              81500.0
P-SAL-02                    2                              79500.0
              Total_Employees  Average_Employee_Salary_per_Project
project_code
P-ENG-01                    5                             111000.0
P-ENG-02                    4                             116250.0

,employee_id,department,hire_date,gender,salary,first_name,last_name,salary_tier,assignment_id,project_code,hours_assigned,project_name,start_date,end_date,budget,status,avg_dept_salary,salary_diff_from_dept
0,101,Engineering,2021-03-15 00:00:00,M,95000.0,John,Smith,2,1.0,P-ENG-01,25.0,Project Alpha,2023-01-15,2023-12-31,500000.0,In Progress,114285.714286,19285.714286
1,101,Engineering,2021-03-15 00:00:00,M,95000.0,John,Smith,2,11.0,P-ENG-02,15.0,Project Beta,2023-03-10,NaT,750000.0,In Progress,114285.714286,19285.714286
2,101,Engineering,2021-03-15 00:00:00,M,95000.0,John,Smith,2,20.0,P-FIN-01,10.0,NaN,NaT,NaT,NaN,NaN,114285.714286,19285.714286
3,102,Marketing,2020-07-22 00:00:00,F,82000.0,Jane,Doe,1,2.0,P-MKT-01,30.0,Marketing Campaign 2023,2023-02-01,2023-06-30,250000.0,Completed,83750.000000,1750.000000
4,102,Marketing,2020-07-22 00:00:00,F,82000.0,Jane,Doe,1,13.0,P-MKT-02,25.0,Social Media Push,2023-05-15,2023-08-31,180000.0,In Progress,83750.000000,1750.000000
5,103,Engineering,Unknown,F,110000.0,Emily,Williams,3,3.0,P-ENG-01,40.0,Project Alpha,2023-01-15,2023-12-31,500000.0,In Progress,114285.714286,4285.714286
6,104,Sales,2022-01-10 00:00:00,M,78000.0,Michael,Brown,1,4.0,P-SAL-01,35.0,Sales Drive Q1,2023-01-01,2023-03-31,150000.0,Completed,82400.000000,4400.000000
7,104,Sales,2022-01-10 00:00:00,M,78000.0,Michael,Brown,1,18.0,P-SAL-02,20.0,Sales Drive Q2,2023-04-01,2023-06-30,160000.0,In Progress,82400.000000,4400.000000
8,105,HR,2019-11-05 00:00:00,F,90000.0,Jessica,Jones,1,5.0,P-HR-01,20.0,HR System Upgrade,2023-04-01,2023-09-30,300000.0,Planning,91000.000000,1000.000000
9,106,Marketing,2023-05-20 00:00:00,M,91000.0,David,Garcia,2,6.0,P-MKT-02,28.0,Social Media Push,2023-05-15,2023-08-31,180000.0,In Progress,83750.000000,7250.000000
10,107,Sales,Unknown,F,81000.0,Sarah,Miller,1,7.0,P-SAL-02,32.0,Sales Drive Q2,2023-04-01,2023-06-30,160000.0,In Progress,82400.000000,1400.000000
11,108,Engineering,2020-09-15 00:00:00,M,125000.0,James,Davis,4,8.0,P-ENG-02,38.0,Project Beta,2023-03-10,NaT,750000.0,In Progress,114285.714286,10714.285714
12,108,Engineering,2020-09-15 00:00:00,M,125000.0,James,Davis,4,16.0,P-ENG-01,10.0,Project Alpha,2023-01-15,2023-12-31,500000.0,In Progress,114285.714286,10714.285714
13,109,HR,2022-08-01 00:00:00,Unknown,91000.0,Maria,Rodriguez,2,9.0,P-HR-01,22.0,HR System Upgrade,2023-04-01,2023-09-30,300000.0,Planning,91000.000000,0.000000
14,110,Sales,2021-12-12 00:00:00,M,85000.0,Robert,Martinez,1,10.0,P-SAL-01,33.0,Sales Drive Q1,2023-01-01,2023-03-31,150000.0,Completed,82400.000000,2600.000000
15,111,Engineering,2023-02-28 00:00:00,F,105000.0,Ashley,Hernandez,3,12.0,P-ENG-01,35.0,Project Alpha,2023-01-15,2023-12-31,500000.0,In Progress,114285.714286,9285.714286
16,112,Marketing,2020-06-18 00:00:00,M,79000.0,William,Lopez,1,14.0,P-MKT-01,32.0,Marketing Campaign 2023,2023-02-01,2023-06-30,250000.0,Completed,83750.000000,4750.000000
17,113,Sales,2022-04-30 00:00:00,F,91000.0,Jennifer,Gonzalez,2,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,82400.000000,8600.000000
18,114,Engineering,2021-07-14 00:00:00,M,115000.0,Richard,Wilson,3,15.0,P-ENG-02,45.0,Project Beta,2023-03-10,NaT,750000.0,In Progress,114285.714286,714.285714
19,115,HR,2019-10-01 00:00:00,F,92000.0,Linda,Anderson,2,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,91000.000000,1000.000000
20,116,Marketing,2022-11-23 00:00:00,M,83000.0,Joseph,Thomas,1,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,83750.000000,750.000000
21,117,Engineering,2020-01-15 00:00:00,F,130000.0,Susan,Taylor,4,17.0,P-ENG-02,50.0,Project Beta,2023-03-10,NaT,750000.0,In Progress,114285.714286,15714.285714
22,118,Sales,2023-03-01 00:00:00,M,77000.0,Charles,Moore,1,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,82400.000000,5400.000000
23,119,HR,2021-09-20 00:00:00,Unknown,91000.0,Patricia,Jackson,2,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,91000.000000,0.000000
24,120,Engineering,2022-06-08 00:00:00,M,120000.0,Christopher,White,4,19.0,P-ENG-01,40.0,Project Alpha,2023-01-15,2023-12-31,500000.0,In Progress,114285.714286,5714.285714

In [ ]:
employees_df.groupby("department")["salary"].mean()

department
Engineering    114285.714286
HR              91000.000000
Marketing       83750.000000
Sales           82400.000000
Name: salary, dtype: float64

# **Assignment - Module 4**

**Question 1**

In [29]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

pd.options.mode.copy_on_write = True

nhl_df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/datasets/Module4 assignments/nhl.csv")
cities=pd.read_html("/content/drive/MyDrive/Colab Notebooks/datasets/Module4 assignments/wikipedia_data.htm")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

def nhl_correlation():
    nhl_df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/datasets/Module4 assignments/nhl.csv")
    cities=pd.read_html("/content/drive/MyDrive/Colab Notebooks/datasets/Module4 assignments/wikipedia_data.htm")[1]
    cities=cities.iloc[:-1,[0,3,5,6,7,8]]
    nhl_df["team"] = nhl_df["team"].str.replace("*","")
    nhl_df = nhl_df[(nhl_df["GP"] == "82") & (nhl_df["year"] == 2018)]
    team_list  = list(nhl_df["team"])
    cities["Metropolitan area"] = cities["Metropolitan area"].str.replace(",","").str.replace("â€“"," ")
    cities_list = list(cities["Metropolitan area"])
    cities = cities.rename(columns={"Population (2016 est.)[8]":"population","Metropolitan area":"city"})

    def matching_teams_with_cities(cities_list,team_list):
      match_dict = {}
      for team in team_list:
        for city in cities_list:
          if team.split()[0] == city:
            match_dict[team] = city
          elif " ".join(team.split()[0:2]) == city:
            match_dict[team] = city
          elif "New York" in team:
            match_dict[team] = "New York City"
          elif "Washington" in team:
            match_dict[team] = "Washington D.C."
          elif "Dallas" in team:
            match_dict[team] = "Dallas Fort Worth"
          elif "Tampa Bay" in team:
            match_dict[team] = "Tampa Bay Area"
          elif "Florida" in team:
            match_dict[team] = "Miami Fort Lauderdale"
          elif "Devils" in team:
            match_dict[team] = "New York City"
          elif "Carolina" in team:
            match_dict[team] = "Raleigh"
          elif "Minnesota" in team:
            match_dict[team] = "Minneapolis Saint Paul"
          elif "Colorado" in team:
            match_dict[team] = "Denver"
          elif "Vegas" in team:
            match_dict[team] = "Las Vegas"
          elif "Anaheim" in team:
            match_dict[team] = "Los Angeles"
          elif "San Jose" in team:
            match_dict[team] = "San Francisco Bay Area"
          elif "Arizona" in team:
            match_dict[team] = "Phoenix"

      return match_dict

    nhl_df["city"] = nhl_df["team"].map(matching_teams_with_cities(cities_list,team_list))
    nhl_df = nhl_df.sort_values(by="city")

    nhl_df = pd.merge(nhl_df,cities[["city","population"]],how="left",on="city")
    nhl_df = nhl_df.set_index(["city","team"])
    nhl_df[["W", "L","population"]] = nhl_df[["W", "L","population"]].apply(pd.to_numeric, errors='coerce')
    nhl_df["wl_ratio"] = nhl_df["W"] / (nhl_df["W"] + nhl_df["L"])
    population_by_region = list(nhl_df.groupby("city").agg({"wl_ratio":"mean","population":"mean"})["population"])
    win_loss_by_region = list(nhl_df.groupby("city").agg({"wl_ratio":"mean","population":"mean"})["wl_ratio"])


    assert len(population_by_region) == len(win_loss_by_region), "Q1: Your lists must be the same length"
    assert len(population_by_region) == 28, "Q1: There should be 28 teams being analysed for NHL"

    return stats.pearsonr(population_by_region, win_loss_by_region)

nhl_correlation()

PearsonRResult(statistic=np.float64(0.012486162921209916), pvalue=np.float64(0.9497182859911804))

**Question 2**

In [34]:
nba_df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/datasets/Module4 assignments/nba.csv")
cities=pd.read_html("/content/drive/MyDrive/Colab Notebooks/datasets/Module4 assignments/wikipedia_data.htm")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

nba_df = nba_df[nba_df["year"] == 2018]
nba_df["team"] = nba_df["team"].replace(to_replace="\*?\s\(\d{1,2}\)",value="",regex=True)
team_list = list(nba_df["team"])
cities["Metropolitan area"] = cities["Metropolitan area"].str.replace(",","").str.replace("â€“"," ")
cities_list = list(cities["Metropolitan area"])
cities = cities.rename(columns={"Population (2016 est.)[8]":"population","Metropolitan area":"city"})

def matching_teams_with_cities(cities_list,team_list):
  match_dict = {}
  for team in team_list:
    for city in cities_list:
      if team.split()[0] == city:
        match_dict[team] = city
      elif " ".join(team.split()[0:2]) == city:
        match_dict[team] = city
      elif "New York" in team:
        match_dict[team] = "New York City"
      elif "Washington" in team:
        match_dict[team] = "Washington D.C."
      elif "Dallas" in team:
        match_dict[team] = "Dallas Fort Worth"
      elif "Tampa Bay" in team:
        match_dict[team] = "Tampa Bay Area"
      elif "Florida" in team:
        match_dict[team] = "Miami Fort Lauderdale"
      elif "Devils" in team:
        match_dict[team] = "New York City"
      elif "Carolina" in team:
        match_dict[team] = "Raleigh"
      elif "Minnesota" in team:
        match_dict[team] = "Minneapolis Saint Paul"
      elif "Colorado" in team:
        match_dict[team] = "Denver"
      elif "Vegas" in team:
        match_dict[team] = "Las Vegas"
      elif "Anaheim" in team:
        match_dict[team] = "Los Angeles"
      elif "San Jose" in team:
        match_dict[team] = "San Francisco Bay Area"
      elif "Arizona" in team:
        match_dict[team] = "Phoenix"
      elif "Indiana" in team:
        match_dict[team] = "Indianapolis"
      elif "Miami" in team:
        match_dict[team] = "Miami Fort Lauderdale"
      elif "Brooklyn" in team:
        match_dict[team] = "New York City"
      elif "Golden State" in team:
        match_dict[team] = "San Francisco Bay Area"
      elif "Utah" in team:
        match_dict[team] = "Salt Lake City"

  return match_dict

nba_df["city"] = nba_df["team"].map(matching_teams_with_cities(cities_list,team_list))
nba_df = nba_df.sort_values(by="city")

nba_df = pd.merge(nba_df,cities[["city","population"]],how="left",on="city")
nba_df = nba_df.set_index(["city","team"])
nba_df[["W", "L","population"]] = nba_df[["W", "L","population"]].apply(pd.to_numeric, errors='coerce')
nba_df["wl_ratio"] = nba_df["W"] / (nba_df["W"] + nba_df["L"])
population_by_region = list(nba_df.groupby("city").agg({"wl_ratio":"mean","population":"mean"})["population"])
win_loss_by_region = list(nba_df.groupby("city").agg({"wl_ratio":"mean","population":"mean"})["wl_ratio"])
stats.pearsonr(population_by_region, win_loss_by_region)

PearsonRResult(statistic=np.float64(-0.17657160252844623), pvalue=np.float64(0.3687474160446291))

**Question 3**

In [31]:
mlb_df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/datasets/Module4 assignments/mlb.csv")
cities=pd.read_html("/content/drive/MyDrive/Colab Notebooks/datasets/Module4 assignments/wikipedia_data.htm")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]
cities["Metropolitan area"] = cities["Metropolitan area"].str.replace(",","").str.replace("â€“"," ")
cities_list = list(cities["Metropolitan area"])
cities = cities.rename(columns={"Population (2016 est.)[8]":"population","Metropolitan area":"city"})
mlb_df = mlb_df[mlb_df["year"] == 2018]
team_list = list(mlb_df["team"])

def matching_teams_with_cities(cities_list,team_list):
  match_dict = {}
  for team in team_list:
    for city in cities_list:
      if team.split()[0] == city:
        match_dict[team] = city
      elif " ".join(team.split()[0:2]) == city:
        match_dict[team] = city
      elif "New York" in team:
        match_dict[team] = "New York City"
      elif "Washington" in team:
        match_dict[team] = "Washington D.C."
      elif "Dallas" in team:
        match_dict[team] = "Dallas Fort Worth"
      elif "Tampa Bay" in team:
        match_dict[team] = "Tampa Bay Area"
      elif "Florida" in team:
        match_dict[team] = "Miami Fort Lauderdale"
      elif "Devils" in team:
        match_dict[team] = "New York City"
      elif "Carolina" in team:
        match_dict[team] = "Raleigh"
      elif "Minnesota" in team:
        match_dict[team] = "Minneapolis Saint Paul"
      elif "Colorado" in team:
        match_dict[team] = "Denver"
      elif "Vegas" in team:
        match_dict[team] = "Las Vegas"
      elif "Anaheim" in team:
        match_dict[team] = "Los Angeles"
      elif "San Jose" in team:
        match_dict[team] = "San Francisco Bay Area"
      elif "Arizona" in team:
        match_dict[team] = "Phoenix"
      elif "Indiana" in team:
        match_dict[team] = "Indianapolis"
      elif "Miami" in team:
        match_dict[team] = "Miami Fort Lauderdale"
      elif "Brooklyn" in team:
        match_dict[team] = "New York City"
      elif "Golden State" in team:
        match_dict[team] = "San Francisco Bay Area"
      elif "Utah" in team:
        match_dict[team] = "Salt Lake City"
      elif "San Francisco" in team:
        match_dict[team] = "San Francisco Bay Area"
      elif "Oakland" in team:
        match_dict[team] = "San Francisco Bay Area"
      elif "Tennessee" in team:
        match_dict[team] = "Nashville"
      elif "Patriots" in team:
        match_dict[team] = "Boston"
      elif "Texas" in team:
        match_dict[team] = "Dallas Fort Worth"
  return match_dict

mlb_df["city"] = mlb_df["team"].map(matching_teams_with_cities(cities_list,team_list))
mlb_df = mlb_df.sort_values(by="city")

mlb_df = pd.merge(mlb_df,cities[["city","population"]],how="left",on="city")
mlb_df = mlb_df.set_index(["city","team"])
mlb_df[["W", "L","population"]] = mlb_df[["W", "L","population"]].apply(pd.to_numeric, errors='coerce')
mlb_df["wl_ratio"] = mlb_df["W"] / (mlb_df["W"] + mlb_df["L"])
population_by_region = list(mlb_df.groupby("city").agg({"wl_ratio":"mean","population":"mean"})["population"])
win_loss_by_region = list(mlb_df.groupby("city").agg({"wl_ratio":"mean","population":"mean"})["wl_ratio"])
stats.pearsonr(population_by_region, win_loss_by_region)

PearsonRResult(statistic=np.float64(0.15027698302669307), pvalue=np.float64(0.4637070337887561))

**Question 4**

In [40]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

nfl_df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/datasets/Module4 assignments/nfl.csv")
cities=pd.read_html("/content/drive/MyDrive/Colab Notebooks/datasets/Module4 assignments/wikipedia_data.htm")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]
cities["Metropolitan area"] = cities["Metropolitan area"].str.replace(",","").str.replace("â€“"," ")
cities_list = list(cities["Metropolitan area"])
cities = cities.rename(columns={"Population (2016 est.)[8]":"population","Metropolitan area":"city"})

nfl_df = nfl_df[nfl_df["year"] == 2018]
nfl_df = nfl_df[(nfl_df["T"] == "0") | (nfl_df["T"] == "1")]
nfl_df["team"] = nfl_df["team"].str.replace("*","").str.replace("+","")
team_list = list(nfl_df["team"])

def matching_teams_with_cities(cities_list,team_list):
  match_dict = {}
  for team in team_list:
    for city in cities_list:
      if team.split()[0] == city:
        match_dict[team] = city
      elif " ".join(team.split()[0:2]) == city:
        match_dict[team] = city
      elif "New York" in team:
        match_dict[team] = "New York City"
      elif "Washington" in team:
        match_dict[team] = "Washington D.C."
      elif "Dallas" in team:
        match_dict[team] = "Dallas Fort Worth"
      elif "Tampa Bay" in team:
        match_dict[team] = "Tampa Bay Area"
      elif "Florida" in team:
        match_dict[team] = "Miami Fort Lauderdale"
      elif "Devils" in team:
        match_dict[team] = "New York City"
      elif "Carolina" in team:
        match_dict[team] = "Raleigh"
      elif "Minnesota" in team:
        match_dict[team] = "Minneapolis Saint Paul"
      elif "Colorado" in team:
        match_dict[team] = "Denver"
      elif "Vegas" in team:
        match_dict[team] = "Las Vegas"
      elif "Anaheim" in team:
        match_dict[team] = "Los Angeles"
      elif "San Jose" in team:
        match_dict[team] = "San Francisco Bay Area"
      elif "Arizona" in team:
        match_dict[team] = "Phoenix"
      elif "Indiana" in team:
        match_dict[team] = "Indianapolis"
      elif "Miami" in team:
        match_dict[team] = "Miami Fort Lauderdale"
      elif "Brooklyn" in team:
        match_dict[team] = "New York City"
      elif "Golden State" in team:
        match_dict[team] = "San Francisco Bay Area"
      elif "Utah" in team:
        match_dict[team] = "Salt Lake City"
      elif "San Francisco" in team:
        match_dict[team] = "San Francisco Bay Area"
      elif "Oakland" in team:
        match_dict[team] = "San Francisco Bay Area"
      elif "Tennessee" in team:
        match_dict[team] = "Nashville"
      elif "Patriots" in team:
        match_dict[team] = "Boston"
  return match_dict

nfl_df["city"] = nfl_df["team"].map(matching_teams_with_cities(cities_list,team_list))
nfl_df = nfl_df.sort_values(by="city")

nfl_df = pd.merge(nfl_df,cities[["city","population"]],how="left",on="city")
nfl_df = nfl_df.set_index(["city","team"])
nfl_df[["W", "L","population"]] = nfl_df[["W", "L","population"]].apply(pd.to_numeric, errors='coerce')
nfl_df["wl_ratio"] = nfl_df["W"] / (nfl_df["W"] + nfl_df["L"])
population_by_region = list(nfl_df.groupby("city").agg({"wl_ratio":"mean","population":"mean"})["population"])
win_loss_by_region = list(nfl_df.groupby("city").agg({"wl_ratio":"mean","population":"mean"})["wl_ratio"])
stats.pearsonr(population_by_region, win_loss_by_region)

PearsonRResult(statistic=np.float64(0.008975826138476629), pvalue=np.float64(0.9631421264351199))

**Question 5**

In [4]:
import pandas as pd
import numpy as np
from scipy.stats import ttest_rel
import re

cities=pd.read_html("/content/drive/MyDrive/Colab Notebooks/datasets/Module4 assignments/wikipedia_data.htm")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]
nfl_df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/datasets/Module4 assignments/nfl.csv")
mlb_df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/datasets/Module4 assignments/mlb.csv")
nba_df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/datasets/Module4 assignments/nba.csv")
nhl_df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/datasets/Module4 assignments/nhl.csv")

cities["Metropolitan area"] = cities["Metropolitan area"].str.replace(",","").str.replace("â€“"," ")
cities_list = list(cities["Metropolitan area"])
cities = cities.rename(columns={"Population (2016 est.)[8]":"population","Metropolitan area":"city"})

def matching_teams_with_cities(cities_list,team_list):
  match_dict = {}
  for team in team_list:
    for city in cities_list:
      if team.split()[0] == city:
        match_dict[team] = city
      elif " ".join(team.split()[0:2]) == city:
        match_dict[team] = city
      elif "New York" in team:
        match_dict[team] = "New York City"
      elif "Washington" in team:
        match_dict[team] = "Washington D.C."
      elif "Dallas" in team:
        match_dict[team] = "Dallas Fort Worth"
      elif "Tampa Bay" in team:
        match_dict[team] = "Tampa Bay Area"
      elif "Florida" in team:
        match_dict[team] = "Miami Fort Lauderdale"
      elif "Devils" in team:
        match_dict[team] = "New York City"
      elif "Carolina" in team:
        match_dict[team] = "Raleigh"
      elif "Minnesota" in team:
        match_dict[team] = "Minneapolis Saint Paul"
      elif "Colorado" in team:
        match_dict[team] = "Denver"
      elif "Vegas" in team:
        match_dict[team] = "Las Vegas"
      elif "Anaheim" in team:
        match_dict[team] = "Los Angeles"
      elif "San Jose" in team:
        match_dict[team] = "San Francisco Bay Area"
      elif "Arizona" in team:
        match_dict[team] = "Phoenix"
      elif "Indiana" in team:
        match_dict[team] = "Indianapolis"
      elif "Miami" in team:
        match_dict[team] = "Miami Fort Lauderdale"
      elif "Brooklyn" in team:
        match_dict[team] = "New York City"
      elif "Golden State" in team:
        match_dict[team] = "San Francisco Bay Area"
      elif "Utah" in team:
        match_dict[team] = "Salt Lake City"
      elif "San Francisco" in team:
        match_dict[team] = "San Francisco Bay Area"
      elif "Oakland" in team:
        match_dict[team] = "San Francisco Bay Area"
      elif "Tennessee" in team:
        match_dict[team] = "Nashville"
      elif "Patriots" in team:
        match_dict[team] = "Boston"
      elif "Texas" in team:
        match_dict[team] = "Dallas Fort Worth"
  return match_dict

nhl_df["team"] = nhl_df["team"].str.replace("*","")
nhl_df = nhl_df[(nhl_df["GP"] == "82") & (nhl_df["year"] == 2018)]
nhl_df["city"] = nhl_df["team"].map(matching_teams_with_cities(cities_list,list(nhl_df["team"])))
nhl_df = nhl_df.sort_values(by="city")
nhl_df = pd.merge(nhl_df,cities[["city","population"]],how="left",on="city")
nhl_df = nhl_df.set_index(["city","team"])
nhl_df[["W", "L","population"]] = nhl_df[["W", "L","population"]].apply(pd.to_numeric, errors='coerce')
nhl_df["nhl_wl_ratio"] = nhl_df["W"] / (nhl_df["W"] + nhl_df["L"])

nba_df = nba_df[nba_df["year"] == 2018]
nba_df["team"] = nba_df["team"].replace(to_replace="\*?\s\(\d{1,2}\)",value="",regex=True)
nba_df["city"] = nba_df["team"].map(matching_teams_with_cities(cities_list,list(nba_df["team"])))
nba_df = nba_df.sort_values(by="city")
nba_df = pd.merge(nba_df,cities[["city","population"]],how="left",on="city")
nba_df = nba_df.set_index(["city","team"])
nba_df[["W", "L","population"]] = nba_df[["W", "L","population"]].apply(pd.to_numeric, errors='coerce')
nba_df["nba_wl_ratio"] = nba_df["W"] / (nba_df["W"] + nba_df["L"])

mlb_df = mlb_df[mlb_df["year"] == 2018]
mlb_df["city"] = mlb_df["team"].map(matching_teams_with_cities(cities_list,list(mlb_df["team"])))
mlb_df = mlb_df.sort_values(by="city")
mlb_df = pd.merge(mlb_df,cities[["city","population"]],how="left",on="city")
mlb_df = mlb_df.set_index(["city","team"])
mlb_df[["W", "L","population"]] = mlb_df[["W", "L","population"]].apply(pd.to_numeric, errors='coerce')
mlb_df["mlb_wl_ratio"] = mlb_df["W"] / (mlb_df["W"] + mlb_df["L"])

nfl_df = nfl_df[nfl_df["year"] == 2018]
nfl_df = nfl_df[(nfl_df["T"] == "0") | (nfl_df["T"] == "1")]
nfl_df["team"] = nfl_df["team"].str.replace("*","").str.replace("+","")
nfl_df["city"] = nfl_df["team"].map(matching_teams_with_cities(cities_list,list(nfl_df["team"])))
nfl_df = nfl_df.sort_values(by="city")
nfl_df = pd.merge(nfl_df,cities[["city","population"]],how="left",on="city")
nfl_df = nfl_df.set_index(["city","team"])
nfl_df[["W", "L","population"]] = nfl_df[["W", "L","population"]].apply(pd.to_numeric, errors='coerce')
nfl_df["nfl_wl_ratio"] = nfl_df["W"] / (nfl_df["W"] + nfl_df["L"])

nfl_and_mlb_df = pd.merge(nfl_df.groupby("city").agg({"nfl_wl_ratio":"mean"}),mlb_df.groupby("city").agg({"mlb_wl_ratio":"mean"}),how="outer",left_index=True,right_index=True)
nba_nfl_and_mlb_df = pd.merge(nfl_and_mlb_df,nba_df.groupby("city").agg({"nba_wl_ratio":"mean"}),how="outer",left_index=True,right_index=True)
nhl_nba_nfl_and_mlb_df = pd.merge(nba_nfl_and_mlb_df,nhl_df.groupby("city").agg({"nhl_wl_ratio":"mean"}),how="outer",left_index=True,right_index=True)

sports = ['NFL', 'NBA', 'NHL', 'MLB']
p_values = pd.DataFrame({k:np.nan for k in sports}, index=sports)

for sport1 in sports:
  for sport2 in sports:
    if sport1 == sport2:
      p_values.loc[sport1, sport2] = np.nan
    else:
      ratio1 = sport1.lower() + "_wl_ratio"
      ratio2 = sport2.lower() + "_wl_ratio"

      series1 = nhl_nba_nfl_and_mlb_df[ratio1]
      series2 = nhl_nba_nfl_and_mlb_df[ratio2]

      t_statistic, p_value = ttest_rel(series1, series2, nan_policy='omit')

      p_values.loc[sport1, sport2] = p_value

p_values

          NFL       NBA       NHL       MLB
NFL       NaN  0.940611  0.024714  0.802069
NBA  0.940611       NaN  0.022297  0.950540
NHL  0.024714  0.022297       NaN  0.000708
MLB  0.802069  0.950540  0.000708       NaN

In [111]:
cities

,city,population,NFL,MLB,NBA,NHL
0,New York City,20153634,Giants Jets[note 1],Yankees Mets[note 2],Knicks Nets,Rangers Islanders Devils[note 3]
1,Los Angeles,13310447,Rams Chargers[note 4],Dodgers Angels,Lakers Clippers,Kings Ducks
2,San Francisco Bay Area,6657982,49ers Raiders[note 6],Giants Athletics,Warriors,Sharks[note 7]
3,Chicago,9512999,Bears[note 8],Cubs White Sox,Bulls[note 9],Blackhawks
4,Dallas Fort Worth,7233323,Cowboys,Rangers,Mavericks,Stars
5,Washington D.C.,6131977,Redskins,Nationals[note 10],Wizards[note 11],Capitals
6,Philadelphia,6070500,Eagles,Phillies[note 12],76ers,Flyers[note 13]
7,Boston,4794447,Patriots[note 14],Red Sox[note 15],Celtics,Bruins
8,Minneapolis Saint Paul,3551036,Vikings,Twins,Timberwolves,Wild[note 16]
9,Denver,2853077,Broncos,Rockies,Nuggets[note 17],Avalanche[note 18]
10,Miami Fort Lauderdale,6066387,Dolphins,Marlins,Heat,Panthers
11,Phoenix,4661537,Cardinals,Diamondbacks,Suns,Coyotes
12,Detroit,4297617,Lions,Tigers[note 20],Pistons[note 21],Red Wings
13,Toronto,5928040,â€” [note 22],Blue Jays,Raptors[note 23],Maple Leafs
14,Houston,6772470,Texans[note 24],Astros,Rockets,â€”
15,Atlanta,5789700,Falcons,Braves,Hawks,[note 25]
16,Tampa Bay Area,3032171,Buccaneers,Rays,â€”,Lightning
17,Pittsburgh,2342299,Steelers,Pirates,[note 27],Penguins[note 28]
18,Cleveland,2055612,Browns[note 29],Indians[note 30],Cavaliers[note 31],[note 32]
19,Seattle,3798902,Seahawks,Mariners,[note 33],[note 34]
20,Cincinnati,2165139,Bengals,Reds[note 35],[note 36],â€”
21,Kansas City,2104509,Chiefs,Royals[note 37],[note 38],[note 39]
22,St. Louis,2807002,[note 40],Cardinals[note 41],[note 42],Blues[note 43]
23,Baltimore,2798886,Ravens[note 45],Orioles[note 46],[note 47],â€”
24,Charlotte,2474314,Panthers,â€”,Hornets[note 49],â€”
25,Indianapolis,2004230,Colts,[note 50],Pacers[note 51],â€”
26,Nashville,1865298,Titans,â€”,â€”,Predators
27,Milwaukee,1572482,[note 53],Brewers[note 54],Bucks,â€”
28,New Orleans,1268883,Saints,â€”,Pelicans[note 55],â€”
29,Buffalo,1132804,Bills[note 56],[note 57],[note 58],Sabres
30,Montreal,4098927,â€”,[note 59],â€”,Canadiens
31,Vancouver,2463431,â€”,â€”,[note 60],Canucks
32,Orlando,2441257,â€”,â€”,Magic,â€”
33,Portland,2424955,â€”,â€”,Trail Blazers,â€”
34,Columbus,2041520,â€”,â€”,â€”,Blue Jackets
35,Calgary,1392609,â€”,â€”,â€”,Flames
36,Ottawa,1323783,â€”,â€”,â€”,Senators
37,Edmonton,1321426,â€”,â€”,â€”,Oilers
38,Salt Lake City,1186187,â€”,â€”,Jazz,â€”
39,Winnipeg,778489,â€”,â€”,â€”,Jets[note 61]
40,San Diego,3317749,[note 62],Padres,[note 63],â€”
41,San Antonio,2429609,[note 64],â€”,Spurs,â€”
42,Sacramento,2296418,â€”,â€”,Kings,â€”
43,Las Vegas,2155664,[note 6],â€”,â€”,Golden Knights
44,Jacksonville,1478212,Jaguars,â€”,â€”,â€”
45,Oklahoma City,1373211,â€”,â€”,Thunder[note 68],â€”
46,Memphis,1342842,[note 69],â€”,Grizzlies,â€”
47,Raleigh,1302946,â€”,â€”,â€”,Hurricanes
48,Green Bay,318236,Packers,â€”,â€”,â€”
49,Hamilton,747545,â€”,â€”,â€”,[note 71]
50,Regina,236481,â€”,â€”,â€”,â€”